name: Release Pipeline

on:
  push:
    tags:
      - 'v*'  # Aciona a pipeline quando uma tag começando com 'v' é empurrada, ex: v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest  # Executa a ação em um ambiente Ubuntu

    steps:
      # Checkout do código
      - name: Checkout Code
        uses: actions/checkout@v2

      # Setando Node.js (caso precise de Node.js para gerenciar dependências, por exemplo)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Instalar dependências (se necessário)
      - name: Install Dependencies
        run: npm install  # Caso seu site use ferramentas como Jekyll ou outros geradores de site

      # Gerar os arquivos finais (por exemplo, se você estiver usando Jekyll, Hugo, etc.)
      - name: Build the Site
        run: npm run build  # Comando para gerar os arquivos, como 'jekyll build' ou 'hugo'

      # Configuração do Git para publicação no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # O branch onde será publicado
          folder: docs  # Pasta contendo os arquivos estáticos gerados

      # Garantir que o repositório está configurado com as permissões adequadas
      - name: Configure Git for Deployment
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'